name: DSRT Build & Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional: basic syntax validation for JS files
      - name: Validate JavaScript syntax
        run: |
          find src demo -name "*.js" -print0 | xargs -0 -n1 node --check

      # Optional: build docs (uncomment if you add JSDoc)
      # - name: Generate JSDoc
      #   run: |
      #     npm install -g jsdoc
      #     jsdoc src -d docs

      # Save the repository for deployment
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dsrt-build
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
